const $=id=>document.getElementById(id);const TZ='America/Denver',MONTH=8,DAY=12;let target=getNextBirthday(),celebrationRunning=false,audioCtx;const AC=window.AudioContext||window.webkitAudioContext;
function mountainYear(){return Number(new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric'}).format(new Date()))}
function birthdayTimestamp(y){return Date.UTC(y,MONTH-1,DAY,6)}
function getNextBirthday(){const y=mountainYear(),t=birthdayTimestamp(y);return Date.now()<t?t:birthdayTimestamp(y+1)}
function update(){const diff=target-Date.now();if(diff<=0){if(!celebrationRunning){celebrationRunning=true;celebration()}return}const s=Math.floor(diff/1000);$('days').textContent=Math.floor(s/86400);$('hours').textContent=Math.floor(s%86400/3600);$('minutes').textContent=Math.floor(s%3600/60);$('seconds').textContent=s%60;const year=mountainYear(),next=birthdayTimestamp(year)+(Date.now()>=birthdayTimestamp(year)?31536000000:0),start=next-31536000000;const hype=Math.max(0,Math.min(100,100-((next-Date.now())/(next-start))*100));$('hypeFill').style.width=hype+'%';$('hypePercent').textContent=Math.round(hype)+'%';updateDayNight()}
function updateDayNight(){const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'2-digit',hourCycle:'h23'}).format(new Date()));document.body.classList.toggle('day',hour>=7&&hour<19)}
function resetCountdown(){target=getNextBirthday();celebrationRunning=false;$('count').style.display='grid';$('celebrate').style.display='none';$('cake').style.display='block';$('title').textContent='Birthday Countdown!';$('subtitle').textContent='Counting down to August 12 at midnight 🎈';update()}
function celebration(){$('title').textContent='🎉 HAPPY BIRTHDAY! 🎉';$('subtitle').textContent='IT’S MIDNIGHT IN MOUNTAIN TIME! 🎂🔊';$('count').style.display='none';$('celebrate').style.display='block';$('cake').classList.add('blown');$('explosion').classList.add('go');confetti(300);balloons();birthdaySound();setTimeout(cheerSound,700);setTimeout(birthdaySound,1500);setTimeout(resetCountdown,10000)}
function beep(f,d,type='sine',v=.12,delay=0){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.001,audioCtx.currentTime+delay);g.gain.linearRampToValueAtTime(v,audioCtx.currentTime+delay+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+delay+d);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+delay);o.stop(audioCtx.currentTime+delay+d+.03)}
function birthdaySound(){if(!audioCtx)return;[523,659,784,1047,1319].forEach((f,i)=>beep(f,.25,'triangle',.13,i*.13))}function cheerSound(){if(!audioCtx)return;[440,554,659,880].forEach((f,i)=>beep(f,.16,'sawtooth',.07,i*.12))}
function confetti(n=100){for(let i=0;i<n;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=`hsl(${Math.random()*360},100%,65%)`;c.style.animationDelay=Math.random()*1.5+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),4500)}}
function balloons(){for(let i=0;i<10;i++){const e=document.createElement('div');e.className='balloon';e.textContent='🎈';e.style.left=Math.random()*100+'vw';e.style.animationDuration=5+Math.random()*6+'s';document.body.appendChild(e);setTimeout(()=>e.remove(),12000)}}
function startAudio(){if(!AC)return;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')audioCtx.resume()}
$('airhorn').onclick=()=>{startAudio();beep(220,.35,'sawtooth',.16);beep(330,.45,'sawtooth',.14,.25)};$('tada').onclick=()=>{startAudio();birthdaySound()};$('cheer').onclick=()=>{startAudio();cheerSound()};$('party').onclick=()=>{startAudio();confetti(150);balloons();cheerSound()};
$('music').onclick=()=>{startAudio();if(audioCtx){birthdaySound();cheerSound()}};
document.querySelectorAll('.gift').forEach(g=>g.onclick=()=>{$('giftMessage').textContent=g.dataset.message;startAudio();beep(784,.3,'triangle',.1)});
let score=0,gameTimer;function spawnBalloon(){const area=$('gameArea'),b=document.createElement('span');b.className='game-balloon';b.textContent='🎈';b.style.left=Math.random()*85+'%';b.style.top=Math.random()*55+'px';b.onclick=()=>{score++;$('score').textContent='Score: '+score;b.remove()};area.appendChild(b);setTimeout(()=>b.remove(),1800)}$('startGame').onclick=()=>{clearInterval(gameTimer);score=0;$('score').textContent='Score: 0';gameTimer=setInterval(spawnBalloon,650);setTimeout(()=>clearInterval(gameTimer),15000)};
const BIRTH_YEAR=2016;function stats(){const now=new Date(),birth=birthdayTimestamp(BIRTH_YEAR),age=Math.floor((Date.now()-birth)/31557600000);$('age').textContent='🎈 Age: '+age;$('daysAlive').textContent='📅 Days since Aug 12, 2016: '+Math.max(0,Math.floor((Date.now()-birth)/86400000)).toLocaleString()}stats();update();setInterval(update,250);